### ISSUE TITLE
Hanoi is being mapped to Asia/Bangkok, not Asia/Ho_Chi_Minh

### ISSUE THREAD

**Issue by nkcanball** [ringsaturn/tzf#163] opened 2024-05-21 10:54 UTC
While they are effectively in the same relative time zone wrt UTC or GMT, I'd expect the correct match here would be Ho Chi Minh and not Bangkok, keeping the match to a location in the same country. 

Is this an error or is there a particular reason for this mapping?

**Comment by ringsaturn** [comment] 2024-05-21 13:10
Please provide the longitude and latitude you are using and I will check this.

**Comment by nkcanball** [comment] 2024-05-21 14:21
Using these for Hanoi, VN: 
lat=21.03, lon=105.85

and initializing the finder with the full dataset from the protobuf

**Comment by ringsaturn** [comment] 2024-05-22 00:47
Hi, I've checked the programs (tzf's Go&Python versions) and found that they return "Asia/Bangkok" as expected, as required by both tzdb and timezone-boundary-builder.

Regarding the timezone-boundary-builder:

The original timezone shape files come from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder). Since version 2019a, the "Split Vietnam into 2 zones" operation has been done. You can read the change log here: [2019a](https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2019a).

Concerning tzdb, it's been a long issue that I've delved into.

- tzdb: https://github.com/eggert/tz/blob/db7fb40dc996c67abedb03fa968a97997f2e4c26/zone1970.tab#L305
- https://mm.icann.org/pipermail/tz/2019-February/052623.html

So it's not a bug; it's by design.

If tzdb changes the timezone information in the future, timezone-boundary-builder will update accordingly, and tzf will use the latest shape data to build.

**Comment by ringsaturn** [comment] 2024-05-25 13:07
I'm going to close this issue within a week if no more questions.

**Closed** 2024-05-29 15:26 UTC
